
select count(*) as 'Total des cas' from jfile.JudicialFile
select count(*) as 'Total open cases' from jfile.JudicialFile where StatusId <> 'Close'
select count(*) as 'Total Close cases' from jfile.JudicialFile where StatusId = 'Close'
select count(*) as 'Total Close cases before 2020-01-01' from jfile.JudicialFile where StatusId = 'Close' and ModifiedDate < '2020-01-01'
select count(*) as 'Total Close cases in ProblemDescription' from jfile.JudicialFile where StatusId = 'Close' and StatusBeforeClosing = 'ProblemDescription'
select count(*) as 'Total Close cases in ProblemDescription before 2020-01-01' from jfile.JudicialFile where StatusId = 'Close' and ModifiedDate < '2020-01-01' and StatusBeforeClosing = 'ProblemDescription'
select count(*) as 'Total Close cases in InitialProposal' from jfile.JudicialFile where StatusId = 'Close' and StatusBeforeClosing = 'InitialProposal'
select count(*) as 'Total Close cases in InitialProposal before 2020-01-01' from jfile.JudicialFile where StatusId = 'Close' and ModifiedDate < '2020-01-01' and StatusBeforeClosing = 'InitialProposal'
select count(*) as 'Total Close cases in InitialDocumentFiling' from jfile.JudicialFile where StatusId = 'Close' and StatusBeforeClosing = 'InitialDocumentFiling'
select count(*) as 'Total Close cases in InitialDocumentFiling before 2020-01-01' from jfile.JudicialFile where StatusId = 'Close' and ModifiedDate < '2020-01-01' and StatusBeforeClosing = 'InitialDocumentFiling'
select count(*) as 'Total Close cases in FilingCompletion' from jfile.JudicialFile where StatusId = 'Close' and StatusBeforeClosing = 'FilingCompletion'
select count(*) as 'Total Close cases in FilingCompletion before 2020-01-01' from jfile.JudicialFile where StatusId = 'Close' and ModifiedDate < '2020-01-01' and StatusBeforeClosing = 'FilingCompletion'
select count(*) as 'Total Close cases in Draft' from jfile.JudicialFile where StatusId = 'Close' and StatusBeforeClosing = 'Draft'
select count(*) as 'Total Close cases in Draft before 2020-01-01' from jfile.JudicialFile where StatusId = 'Close' and ModifiedDate < '2020-01-01' and StatusBeforeClosing = 'Draft'
select count(*) as 'Total Close cases in Negotiation' from jfile.JudicialFile where StatusId = 'Close' and StatusBeforeClosing = 'Negotiation'
select count(*) as 'Total Close cases in Negotiation before 2020-01-01' from jfile.JudicialFile where StatusId = 'Close' and ModifiedDate < '2020-01-01' and StatusBeforeClosing = 'Negotiation'
select count(*) as 'Total Close cases in Mediation' from jfile.JudicialFile where StatusId = 'Close' and StatusBeforeClosing = 'Mediation'
select count(*) as 'Total Close cases in Mediation before 2020-01-01' from jfile.JudicialFile where StatusId = 'Close' and ModifiedDate < '2020-01-01' and StatusBeforeClosing = 'Mediation'
select count(*) as 'Total Close cases in MediationRequest' from jfile.JudicialFile where StatusId = 'Close' and StatusBeforeClosing = 'MediationRequest'
select count(*) as 'Total Close cases in MediationRequest before 2020-01-01' from jfile.JudicialFile where StatusId = 'Close' and ModifiedDate < '2020-01-01' and StatusBeforeClosing = 'MediationRequest'
select count(*) as 'Total Close cases in MediatorAssign' from jfile.JudicialFile where StatusId = 'Close' and StatusBeforeClosing = 'MediatorAssign'
select count(*) as 'Total Close cases in MediatorAssign before 2020-01-01' from jfile.JudicialFile where StatusId = 'Close' and ModifiedDate < '2020-01-01' and StatusBeforeClosing = 'MediatorAssign'